### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by HannesTheDev** [CrowBaldeYT/RankSystem#1]
Coole Idee ein Deutsches Rang System zu machen! Viel Erfolg noch!

**Comment by CrowBaldeYT** [comment]
Da ist halt leider ein Fehler der schwer zu beheben ist

**Comment by HannesTheDev** [comment]
Wo denn? Vllt kann ich ja helfen

**Comment by CrowBaldeYT** [comment]
return self::getDataFolder();

**Comment by CrowBaldeYT** [comment]
das geht in einer static function nicht

**Comment by CrowBaldeYT** [comment]
in der api.php datei

**Comment by HannesTheDev** [comment]
Ja mist leider kenne ich micht nicht so mit APIs aus

**Comment by CrowBaldeYT** [comment]
Gefixt

**Comment by Ju999** [comment]
Nice!

**Comment by CrowBaldeYT** [comment]
Klappt trzdm. Nicht ...
